### ISSUE TITLE
При включенной песочнице у пользователей с низким рейтингом пропадает возможность просмотра черновиков

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/alto-plugin-sandbox#1]
При включенной песочнице нельзя просмотреть список черновиков на странице /content/drafts/, так как после сохранения топика ему присваевается статус публикации в песочнице (define('TOPIC_STATUS_SANDBOX', 20);), у кого рейтинга хватает миновать песочницу, у тех черновики работают нормально.

**Comment by aVadim483** [comment]
Что-то не могу воспроизвести проблему.

Захожу на сайт под юзером с нулевым рейтингом. Создаю статью и сохраняю ее в черновике. Иду на страницу /content/drafts/ и вижу ленту с этой страницей.

Как воспроизвести?

**Comment by bambarbia-kergudu** [comment]
Ради чистоты эксперимента установил версию 1.1.12 с репозитория и проделал следующие действия: включаем песочницу, регистрируемся под новым участником (проверяем не под админом, он не подпадает под критерии песочницы), переходим на страницу создания нового топика (http://alto1112.ru/content/topic/add/), выбираем категорию, заполняем заголовок и тело топика, сохраняем топик сразу в черновики. Переходим на страницу со списком черновиков - http://alto1112.ru/content/drafts/ , выскакивает сообщение "Сюда еще никто не успел написать", хотя на счетчике черновиков горит единица. Если перейти на страницу ленты комментариев (http://alto1112.ru/feed/track/), запись с черновиком есть, и в нее можно попасть "только" отсюда.

**Comment by aVadim483** [comment]
fixed https://github.com/altocms/alto-plugin-sandbox/commit/a24679cff443f9bf3285517d8ff41dcc21071e27

**Comment by bambarbia-kergudu** [comment]
Спасибо, Вадим. Проблема решена.
